language: node_js

node_js:
  - "7.9.0"

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  - chmod a+x deploy.sh compile.sh
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "ec0fc977c305"
  - COMMIT_AUTHOR_EMAIL: "vincentsylo@gmail.com"
